//
// Created by Michael on 20/8/2021.
//

#ifndef EXTRACLASE_N1_DATOS_II_PAGGEDARRAY_H
#define EXTRACLASE_N1_DATOS_II_PAGGEDARRAY_H

#endif //EXTRACLASE_N1_DATOS_II_PAGGEDARRAY_H

class PagedArray{

};
